/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package proj.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int Bool = 6;
  /** RegularExpression Id. */
  int LinBool = 7;
  /** RegularExpression Id. */
  int NIL = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int STAR = 11;
  /** RegularExpression Id. */
  int DIV = 12;
  /** RegularExpression Id. */
  int LPAR = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int LCRL = 15;
  /** RegularExpression Id. */
  int RCRL = 16;
  /** RegularExpression Id. */
  int LBRA = 17;
  /** RegularExpression Id. */
  int RBRA = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int CONS = 22;
  /** RegularExpression Id. */
  int LCONS = 23;
  /** RegularExpression Id. */
  int SEMIC = 24;
  /** RegularExpression Id. */
  int TERM = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int VERT = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int EQ = 30;
  /** RegularExpression Id. */
  int GT = 31;
  /** RegularExpression Id. */
  int LT = 32;
  /** RegularExpression Id. */
  int GTEQ = 33;
  /** RegularExpression Id. */
  int LTEQ = 34;
  /** RegularExpression Id. */
  int DIF = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int ELSE = 38;
  /** RegularExpression Id. */
  int PRINT = 39;
  /** RegularExpression Id. */
  int PRINTLN = 40;
  /** RegularExpression Id. */
  int FN = 41;
  /** RegularExpression Id. */
  int LFN = 42;
  /** RegularExpression Id. */
  int ARROW = 43;
  /** RegularExpression Id. */
  int DLOLLIPOP = 44;
  /** RegularExpression Id. */
  int LOLLIPOP = 45;
  /** RegularExpression Id. */
  int SLIMARROW = 46;
  /** RegularExpression Id. */
  int TENSOR = 47;
  /** RegularExpression Id. */
  int PAIR = 48;
  /** RegularExpression Id. */
  int MATCH = 49;
  /** RegularExpression Id. */
  int TYPE = 50;
  /** RegularExpression Id. */
  int TINT = 51;
  /** RegularExpression Id. */
  int TUNIT = 52;
  /** RegularExpression Id. */
  int TBOOL = 53;
  /** RegularExpression Id. */
  int TLBOOL = 54;
  /** RegularExpression Id. */
  int TSTRING = 55;
  /** RegularExpression Id. */
  int TLIST = 56;
  /** RegularExpression Id. */
  int TUNION = 57;
  /** RegularExpression Id. */
  int TSTRUCT = 58;
  /** RegularExpression Id. */
  int TLSTRUCT = 59;
  /** RegularExpression Id. */
  int TTENSOR = 60;
  /** RegularExpression Id. */
  int TPAIR = 61;
  /** RegularExpression Id. */
  int TLINT = 62;
  /** RegularExpression Id. */
  int SPLIT = 63;
  /** RegularExpression Id. */
  int LABEL = 64;
  /** RegularExpression Id. */
  int String = 65;
  /** RegularExpression Id. */
  int Id = 66;
  /** RegularExpression Id. */
  int LinNum = 67;
  /** RegularExpression Id. */
  int Num = 68;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "<Bool>",
    "<LinBool>",
    "\"nil\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\"::\"",
    "\":?\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"lfn\"",
    "\"=>\"",
    "\"=o\"",
    "\"-o\"",
    "\"->\"",
    "\"@\"",
    "\"&\"",
    "\"match\"",
    "\"type\"",
    "\"int\"",
    "\"()\"",
    "\"bool\"",
    "\"linbool\"",
    "\"string\"",
    "\"list\"",
    "\"union\"",
    "\"struct\"",
    "\"lstruct\"",
    "\"tensor\"",
    "\"pair\"",
    "\"linint\"",
    "\"split\"",
    "<LABEL>",
    "<String>",
    "<Id>",
    "<LinNum>",
    "<Num>",
  };

}
